dist: xenial
sudo: false #disable sudo in scripts
language: cpp
python: "3.7"

compiler: 
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - cmake
    - cmake-data 
script:
    - ./build_project.py

#
#deploy:
#  provider: script
#  skip_cleanup: true
#  script:
#    - curl -f -T allocator_self_v2-0.1.$TRAVIS_BUILD_NUMBER-Linux.deb -udimkush:$BINTRAY_API_KEY "https://api.bintray.com/content/dimkush/filters/ip_filter_csv/$TRAVIS_BUILD_NUMBER/ip_filter_csv-$MAJOR_VERSION.$MINOR_VERSION.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"